08/08/2022 01:04:32|INFO    |root                            |BAZARR Finished searching for missing Series Subtitles. Check History for more information.|
08/08/2022 01:37:27|INFO    |root                            |BAZARR Finished searching for missing Movies Subtitles. Check History for more information.|
08/08/2022 04:00:02|INFO    |root                            |BAZARR All existing episode subtitles indexed from disk.|
08/08/2022 04:04:32|INFO    |root                            |BAZARR Finished searching for missing Series Subtitles. Check History for more information.|
08/08/2022 04:37:27|INFO    |root                            |BAZARR Finished searching for missing Movies Subtitles. Check History for more information.|
08/08/2022 05:00:00|INFO    |root                            |BAZARR All existing movie subtitles indexed from disk.|
08/08/2022 07:04:32|INFO    |root                            |BAZARR Finished searching for missing Series Subtitles. Check History for more information.|
08/08/2022 07:37:27|INFO    |root                            |BAZARR Finished searching for missing Movies Subtitles. Check History for more information.|
08/08/2022 09:49:19|WARNING |retry.api                       |HTTPConnectionPool(host='sapidb.caretas.club', port=80): Max retries exceeded with url: /movie?query=French+Kiss&year=1995 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f70109838b0>, 'Connection to sapidb.caretas.club timed out. (connect timeout=10)')), retrying in 5 seconds...|
08/08/2022 09:49:34|WARNING |retry.api                       |HTTPConnectionPool(host='sapidb.caretas.club', port=80): Max retries exceeded with url: /movie?query=French+Kiss&year=1995 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7010a49dc0>, 'Connection to sapidb.caretas.club timed out. (connect timeout=10)')), retrying in 5 seconds...|
08/08/2022 09:49:49|INFO    |root                            |Throttling sucha for 1 hour, until 22/08/08 10:49, because of: ConnectTimeout. Exception info: MaxRetryError("HTTPConnectionPool(host='sapidb.caretas.club', port=80): Max retries exceeded with url: /movie?query=French+Kiss&year=1995 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f70109911f0>, 'Connection to sapidb.caretas.club timed out. (connect timeout=10)'))")|
08/08/2022 09:49:49|INFO    |root                            |BAZARR Finished searching for Subtitles to upgrade. Check History for more information.|
08/08/2022 10:04:32|INFO    |root                            |BAZARR Finished searching for missing Series Subtitles. Check History for more information.|
08/08/2022 10:37:28|INFO    |root                            |BAZARR Finished searching for missing Movies Subtitles. Check History for more information.|
08/08/2022 13:04:32|INFO    |root                            |BAZARR Finished searching for missing Series Subtitles. Check History for more information.|
08/08/2022 13:30:17|INFO    |root                            |Using sucha again after 1 hour, (disabled because: ConnectTimeout)|
08/08/2022 13:37:28|INFO    |root                            |BAZARR Finished searching for missing Movies Subtitles. Check History for more information.|
08/08/2022 16:04:32|INFO    |root                            |BAZARR Finished searching for missing Series Subtitles. Check History for more information.|
08/08/2022 16:37:27|INFO    |root                            |BAZARR Finished searching for missing Movies Subtitles. Check History for more information.|
08/08/2022 21:11:02|WARNING |apscheduler.executors.default   |Run time of job "Update Movie list from Radarr (trigger: interval[1:00:00], next run at: 2022-08-08 21:38:37 -05)" was missed by 0:32:24.246075|
08/08/2022 21:11:02|WARNING |apscheduler.executors.default   |Run time of job "Update Series list from Sonarr (trigger: interval[1:00:00], next run at: 2022-08-08 21:39:28 -05)" was missed by 0:31:33.251508|
08/08/2022 21:11:02|WARNING |apscheduler.executors.default   |Run time of job "Update Release Info (trigger: interval[3:00:00], next run at: 2022-08-08 22:15:20 -05)" was missed by 1:55:41.263093|
08/08/2022 21:11:02|WARNING |apscheduler.executors.default   |Run time of job "Search for wanted Series Subtitles (trigger: interval[3:00:00], next run at: 2022-08-08 22:04:32 -05)" was missed by 2:06:29.256973|
08/08/2022 21:11:02|WARNING |apscheduler.executors.default   |Run time of job "Search for wanted Movies Subtitles (trigger: interval[3:00:00], next run at: 2022-08-08 22:37:27 -05)" was missed by 1:33:34.270301|
08/08/2022 21:11:02|WARNING |apscheduler.executors.default   |Run time of job "Cache maintenance (trigger: interval[1 day, 0:00:00], next run at: 2022-08-09 20:33:55 -05)" was missed by 0:37:06.276200|
08/08/2022 21:11:02|WARNING |apscheduler.executors.default   |Run time of job "Sync episodes with Sonarr (trigger: interval[1:00:00], next run at: 2022-08-08 21:39:32 -05)" was missed by 0:31:29.252061|
08/08/2022 21:36:34|WARNING |retry.api                       |HTTPSConnectionPool(host='www.subtitulamos.tv', port=443): Read timed out. (read timeout=10), retrying in 5 seconds...|
08/08/2022 21:36:42|WARNING |retry.api                       |HTTPSConnectionPool(host='subscene.com', port=443): Read timed out. (read timeout=10), retrying in 5 seconds...|
08/08/2022 21:36:44|WARNING |retry.api                       |HTTPSConnectionPool(host='www.subdivx.com', port=443): Read timed out. (read timeout=20), retrying in 5 seconds...|
08/08/2022 21:38:13|INFO    |root                            |Throttling subscene for 10 minutes, until 22/08/08 21:48, because of: ProviderError. Exception info: 'Something went wrong when trying to log in #1'|
08/08/2022 21:49:09|ERROR   |apscheduler.executors.default   |Job "Upgrade previously downloaded Subtitles (trigger: interval[12:00:00], next run at: 2022-08-09 09:49:08 -05)" raised an exception|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/../libs/apscheduler/executors/base.py", line 125, in run_job\n    retval = job.func(*job.args, **job.kwargs)\n  File "/app/bazarr/bin/bazarr/subtitles/upgrade.py", line 69, in upgrade_subtitles\n    int(upgradable_episode[\'score\'])\nTypeError: int() argument must be a string, a bytes-like object or a number, not \'NoneType\''|
08/08/2022 22:04:33|INFO    |root                            |BAZARR Finished searching for missing Series Subtitles. Check History for more information.|
08/08/2022 22:26:07|INFO    |root                            |Using subscene again after 10 minutes, (disabled because: ProviderError)|
08/08/2022 22:37:28|INFO    |root                            |BAZARR Finished searching for missing Movies Subtitles. Check History for more information.|
